version: '3.8'
services:
  awesome-db:
    image: postgres:13-alpine
    container_name: awesome-db
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_USER: awesomeUser
      POSTGRES_PASSWORD: awesomePass@123
      POSTGRES_DB: awesomeDB
    networks:
     - awesomeNetwork
  awesome-server:
    container_name: awesome-server
    build: .
    image: an-awesome-api
    ports:
      - 3001:3001
    env_file:
      - ./.env.develop
    command: npm run docker-start
    restart: always
    networks:
     - awesomeNetwork
    depends_on:
      - awesome-db
networks:
  awesomeNetwork:
    name: awesomeNetwork
